name: hospital_appointment_app
description: A Flutter application for scheduling hospital appointments.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependencias adicionales pueden ser añadidas aquí
  # Ejemplo:
  # http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Para la generación de código de clases como parte de Flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/ # Si tienes imágenes locales, las puedes colocar aquí
